### PR TITLE
feat: make hero fancy

### PR DESCRIPTION
**Pull request by zeitiv**

### CODE REVIEW

**Review by D3PSI — APPROVED** [review]
we still need to add the ts-particles dependency to be buildable again, other than that, this looks good

**Review by D3PSI — DISMISSED** [review]

**Comment by D3PSI** [comment]
liking how this is starting to look. let's tone it down a bit, add some geometric lines and put this as a general background for the whole landing and auth pages

**Comment by theArgex** [comment]
> liking how this is starting to look. let's tone it down a bit, add some geometric lines and put this as a general background for the whole landing and auth pages
Thank you. Will do.

**Comment by cedricschwyter** [comment]
any updates on this?

**Pull request closed without merging**
